//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int AppId { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string MobNo { get; set; }
        public string Email { get; set; }
        public string Graduation { get; set; }
        public string UGBranch { get; set; }
        public string UGCollege { get; set; }
        public string UGYOP { get; set; }
        public Nullable<decimal> UGPercentage { get; set; }
        public string UGGrade { get; set; }
        public string PostGraduation { get; set; }
        public string PGBranch { get; set; }
        public string PGCollege { get; set; }
        public string PGYOP { get; set; }
        public Nullable<decimal> PGPercentage { get; set; }
        public string PGGrade { get; set; }
        public string Technology { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Resume { get; set; }
    }
}
