//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientinfo
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string mob { get; set; }
        public string type { get; set; }
        public string project { get; set; }
        public string register { get; set; }
        public string deadline { get; set; }
        public string completed_on { get; set; }
        public string Total { get; set; }
        public string paid_amount { get; set; }
        public string balance { get; set; }
    }
}
