//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esankal1_esankalpEntities : DbContext
    {
        public esankal1_esankalpEntities()
            : base("name=esankal1_esankalpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityDigi> ActivityDigis { get; set; }
        public virtual DbSet<Apply> Applies { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Clientinfo> Clientinfoes { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<enquiry> enquiries { get; set; }
        public virtual DbSet<expense> expenses { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<FeedBack1> FeedBacks1 { get; set; }
        public virtual DbSet<feedbk> feedbks { get; set; }
        public virtual DbSet<InternshipRegistration> InternshipRegistrations { get; set; }
        public virtual DbSet<invoicingContact> invoicingContacts { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<mytableDigi> mytableDigis { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<Portfollio> Portfollios { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<project1> projects1 { get; set; }
        public virtual DbSet<projecttask> projecttasks { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Studentfee> Studentfees { get; set; }
        public virtual DbSet<studenttraining> studenttrainings { get; set; }
        public virtual DbSet<tblexpencess> tblexpencesses { get; set; }
        public virtual DbSet<tblIncome> tblIncomes { get; set; }
        public virtual DbSet<tblSM> tblSMS { get; set; }
        public virtual DbSet<TrainingSession> TrainingSessions { get; set; }
        public virtual DbSet<Enquriry> Enquriries { get; set; }
    }
}
