//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public int Id { get; set; }
        public string descrip { get; set; }
        public string dates { get; set; }
        public string month { get; set; }
        public decimal expenses { get; set; }
    }
}
