//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack1
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Review { get; set; }
        public string OverAllExperience { get; set; }
        public string Teaching { get; set; }
        public string OurSupport { get; set; }
        public string OverallSatisfaction { get; set; }
        public string Consultancy { get; set; }
        public string Type { get; set; }
        public int Rating { get; set; }
        public string Extra { get; set; }
        public Nullable<System.DateTime> post_date { get; set; }
    }
}
