//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public string Name { get; set; }
        public string MobNo { get; set; }
        public string Email { get; set; }
        public string Technology { get; set; }
        public string Office { get; set; }
        public string CompSelected { get; set; }
        public string Feedback1 { get; set; }
        public string Image { get; set; }
    }
}
