//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipRegistration
    {
        public int RegId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Education { get; set; }
        public decimal Percentage { get; set; }
        public string Service { get; set; }
        public string Technology { get; set; }
        public string Office { get; set; }
        public string College { get; set; }
        public string Address { get; set; }
    }
}
