//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int NoticeId { get; set; }
        public string NoticeTitle { get; set; }
        public string NoticeDetails { get; set; }
        public string NoticeIncharge { get; set; }
        public string NoticeDate { get; set; }
        public string ExpiryDate { get; set; }
    }
}
