//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project1
    {
        public int Id { get; set; }
        public string Project { get; set; }
        public string Description { get; set; }
        public string ClientName { get; set; }
        public System.DateTime StartDate { get; set; }
        public decimal Duration { get; set; }
        public string Developer { get; set; }
    }
}
