//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectId { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
        public decimal Price { get; set; }
        public string Technology { get; set; }
        public string Image { get; set; }
        public string Upload { get; set; }
    }
}
