//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIncome
    {
        public int IncomeId { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Category { get; set; }
        public decimal Total { get; set; }
    }
}
